---
title: "RStudio Conference 2020 Agenda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, eval=FALSE}
library(googlesheets4)

agenda <- read_sheet(as_sheets_id("1BOuN7xu60VPFjlN6HU1QN2spQJcwwCiLoSMPQ9HZwmo"))

readr::write_rds(agenda, "agenda.rds")
```

```{r, message=FALSE}
library(tidyverse)
library(glue)
library(paletteer)
library(prismatic)
library(htmltools)

pal <- paletteer_d("Polychrome::alphabet") %>%
  clr_lighten(space = "combined", 0.8)

agenda <- read_rds("agenda.rds") %>%
  dplyr::filter(Start > "2020-01-29") %>%
  mutate(color = pal[as.numeric(fct_explicit_na(as.factor(Category)))])

whole_agenda <- agenda %>%
  split(agenda$Start) %>%
  map(~ .x %>% arrange(Category))
```

```{css}
/* Font */
@import url(https://fonts.googleapis.com/css?family=Montserrat);

/* Design */
*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  background-color: #ecf9ff;
}

body {
  color: #222222;
  font-family: 'Montserrat', serif;
  font-style: normal;
  font-weight: 400;
  letter-spacing: 0;
  padding: 1rem;
}

.main{
  max-width: 1200px;
  margin: 0 auto;
}

h1 {
  color: #272727;
    font-size: 24px;
    font-weight: 400;
    text-align: center;
}

h4 {
  color: #272727;
}

.cards {
  display: flex;
  flex-wrap: wrap;
  list-style: none;
  margin: 0;
  padding: 0;
}

.cards_item {
  display: flex;
  padding: 1rem;
}

@media (min-width: 40rem) {
  .cards_item {
    width: 50%;
  }
}

@media (min-width: 56rem) {
  .cards_item {
    width: 25%;
  }
}

.card {
  background-color: white;
  border-radius: 0.25rem;
  box-shadow: 0 20px 40px -14px rgba(0, 0, 0, 0.25);
  display: flex;
  width: 100%;
  flex-direction: column;
  overflow: hidden;
}

.card_content {
  padding: 1rem;
}

.card_title {
  color: #222222;
  font-size: 1.3rem;
  font-weight: 700;
  letter-spacing: 1px;
  text-transform: capitalize;
  margin: 0px;
}

.card_speaker {
  color: #222222;
  font-size: 1rem;
  font-weight: 700;
  letter-spacing: 1px;
  text-transform: capitalize;
  margin: 0px;
}

.card_text {
  color: #222222;
  font-size: 0.875rem;
  line-height: 1.5;
  margin-bottom: 1.25rem;    
  font-weight: 400;
}

.details {
    color: #222222;
    font-size: 0.875rem;
    line-height: 1.5;
    margin-bottom: 1.25rem;
    font-weight: 400;
}

.made_by{
  font-weight: 400;
  font-size: 13px;
  margin-top: 35px;
  text-align: center;
}
```

```{r, echo=FALSE}
# https://codepen.io/mhrkit/pen/GGqdvr
card <- function(x, width) {
  
  if (is.na(x$DescriptionText)) {
    desction_element <- withTags(p(class = "card_text"))
  } else {
    description <- str_wrap(x$DescriptionText, 150) %>%
      str_split("\n")

    desction_element <- withTags(
      p(class = "card_text", 
        details(tags$summary(description[[1]][1]),
                paste0(description[[1]][-1], collapse = " ")))
      )
  }
  
  
  withTags(
    li(class = "cards_item", style = glue("width: {width}%;"),
    div(class = "card", style = glue("background: {x$color};"),
        div(class = "card_content", 
            style = glue("background: {x$color};"),
            h2(class = "card_title", x$Name),
            h3(class = "card_speaker", glue("Speaker: {x$Speaker}")),
            h3(class = "card_speaker", glue("Location: {x$Location}")),
            h3(class = "card_speaker", glue("Category: {x$Category}")),
            desction_element
            )
        )
    )
  )
}

card_row <- function(df) {
  start <- df$Start[1]
  end <- str_remove(df$End[1], '\\d{4}-\\d{2}-\\d{2} ')
  div(h3(glue("Time: {start} - {end}")),
  div(class = "cards", slide::slide(df, card, width = 100 / nrow(df)))
  )
}
```

```{r}
div(
  map(whole_agenda, card_row)
)
```
